export const borderWidth = {
  border: {borderWidth: 1},
  'border-0': {borderWidth: 0},
  'border-2': {borderWidth: 2},
  'border-4': {borderWidth: 4},
  'border-8': {borderWidth: 8},
  'border-x-0': {borderLeftWidth: 0, borderRightWidth: 0},
  'border-x-2': {borderLeftWidth: 2, borderRightWidth: 2},
  'border-x-4': {borderLeftWidth: 4, borderRightWidth: 4},
  'border-x-8': {borderLeftWidth: 8, borderRightWidth: 8},
  'border-x': {borderWidth: 1, borderVerticalWidth: 1},
  'border-y-0': {borderTopWidth: 0, borderBottomWidth: 0},
  'border-y-2': {borderTopWidth: 2, borderBottomWidth: 2},
  'border-y-4': {borderTopWidth: 4, borderBottomWidth: 4},
  'border-y-8': {borderTopWidth: 8, borderBottomWidth: 8},
  'border-y': {borderWidth: 1, borderHorizontalWidth: 1},
  'border-s-0': {borderInlineStartWidth: 0, borderInlineEndWidth: 0},
  'border-s-2': {borderInlineStartWidth: 2, borderInlineEndWidth: 2},
  'border-s-4': {borderInlineStartWidth: 4, borderInlineEndWidth: 4},
  'border-s-8': {borderInlineStartWidth: 8, borderInlineEndWidth: 8},
  'border-s': {borderInlineWidth: 1},
  'border-e-0': {borderInlineEndWidth: 0},
  'border-e-2': {borderInlineEndWidth: 2},
  'border-e-4': {borderInlineEndWidth: 4},
  'border-e-8': {borderInlineEndWidth: 8},
  'border-e': {borderInlineWidth: 1},
  'border-t-0': {borderTopWidth: 0},
  'border-t-2': {borderTopWidth: 2},
  'border-t-4': {borderTopWidth: 4},
  'border-t-8': {borderTopWidth: 8},
  'border-t': {borderTopWidth: 1},
  'border-r-0': {borderRightWidth: 0},
  'border-r-2': {borderRightWidth: 2},
  'border-r-4': {borderRightWidth: 4},
  'border-r-8': {borderRightWidth: 8},
  'border-r': {borderWidth: 1},
  'border-b-0': {borderBottomWidth: 0},
  'border-b-2': {borderBottomWidth: 2},
  'border-b-4': {borderBottomWidth: 4},
  'border-b-8': {borderBottomWidth: 8},
  'border-b': {borderBottomWidth: 1},
  'border-l-0': {borderLeftWidth: 0},
  'border-l-2': {borderLeftWidth: 2},
  'border-l-4': {borderLeftWidth: 4},
  'border-l-8': {borderLeftWidth: 8},
  'border-l': {borderWidth: 1},
};

export const borderStyles = {
  'border-solid': {borderStyle: 'solid'},
  'border-dashed': {borderStyle: 'dashed'},
  'border-dotted': {borderStyle: 'dotted'},
  'border-double': {borderStyle: 'double'},
  'border-hidden': {borderStyle: 'hidden'},
  'border-none': {borderStyle: 'none'},
};

export const borderRounded = {
  'rounded-none': {borderRadius: 0},
  'rounded-sm': {borderRadius: 2},
  rounded: {borderRadius: 4},
  'rounded-md': {borderRadius: 6},
  'rounded-lg': {borderRadius: 8},
  'rounded-xl': {borderRadius: 12},
  'rounded-2xl': {borderRadius: 16},
  'rounded-3xl': {borderRadius: 24},
  'rounded-full': {borderRadius: 9999},
  'rounded-s-none': {borderStartStartRadius: 0, borderEndStartRadius: 0},
  'rounded-s-sm': {borderStartStartRadius: 2, borderEndStartRadius: 2},
  'rounded-s': {borderStartStartRadius: 4, borderEndStartRadius: 4},
  'rounded-s-md': {borderStartStartRadius: 6, borderEndStartRadius: 6},
  'rounded-s-lg': {borderStartStartRadius: 8, borderEndStartRadius: 8},
  'rounded-s-xl': {borderStartStartRadius: 12, borderEndStartRadius: 12},
  'rounded-s-2xl': {borderStartStartRadius: 16, borderEndStartRadius: 16},
  'rounded-s-3xl': {borderStartStartRadius: 24, borderEndStartRadius: 24},
  'rounded-s-full': {borderStartStartRadius: 9999, borderEndStartRadius: 9999},
  'rounded-e-none': {borderStartEndRadius: 0, borderEndEndRadius: 0},
  'rounded-e-sm': {borderStartEndRadius: 2, borderEndEndRadius: 2},
  'rounded-e': {borderStartEndRadius: 4, borderEndEndRadius: 4},
  'rounded-e-md': {borderStartEndRadius: 6, borderEndEndRadius: 6},
  'rounded-e-lg': {borderStartEndRadius: 8, borderEndEndRadius: 8},
  'rounded-e-xl': {borderStartEndRadius: 12, borderEndEndRadius: 12},
  'rounded-e-2xl': {borderStartEndRadius: 16, borderEndEndRadius: 16},
  'rounded-e-3xl': {borderStartEndRadius: 24, borderEndEndRadius: 24},
  'rounded-e-full': {borderStartEndRadius: 9999, borderEndEndRadius: 9999},
  'rounded-t-none': {borderTopLeftRadius: 0, borderTopRightRadius: 0},
  'rounded-t-sm': {borderTopLeftRadius: 2, borderTopRightRadius: 2},
  'rounded-t': {borderTopLeftRadius: 4, borderTopRightRadius: 4},
  'rounded-t-md': {borderTopLeftRadius: 6, borderTopRightRadius: 6},
  'rounded-t-lg': {borderTopLeftRadius: 8, borderTopRightRadius: 8},
  'rounded-t-xl': {borderTopLeftRadius: 12, borderTopRightRadius: 12},
  'rounded-t-2xl': {borderTopLeftRadius: 16, borderTopRightRadius: 16},
  'rounded-t-3xl': {borderTopLeftRadius: 24, borderTopRightRadius: 24},
  'rounded-t-full': {borderTopLeftRadius: 9999, borderTopRightRadius: 9999},
  'rounded-r-none': {borderTopRightRadius: 0, borderBottomRightRadius: 0},
  'rounded-r-sm': {borderTopRightRadius: 2, borderBottomRightRadius: 2},
  'rounded-r': {borderTopRightRadius: 4, borderBottomRightRadius: 4},
  'rounded-r-md': {borderTopRightRadius: 6, borderBottomRightRadius: 6},
  'rounded-r-lg': {borderTopRightRadius: 8, borderBottomRightRadius: 8},
  'rounded-r-xl': {borderTopRightRadius: 12, borderBottomRightRadius: 12},
  'rounded-r-2xl': {borderTopRightRadius: 16, borderBottomRightRadius: 16},
  'rounded-r-3xl': {borderTopRightRadius: 24, borderBottomRightRadius: 24},
  'rounded-r-full': {borderTopRightRadius: 9999, borderBottomRightRadius: 9999},
  'rounded-b-none': {borderBottomRightRadius: 0, borderBottomLeftRadius: 0},
  'rounded-b-sm': {borderBottomRightRadius: 2, borderBottomLeftRadius: 2},
  'rounded-b': {borderBottomRightRadius: 4, borderBottomLeftRadius: 4},
  'rounded-b-md': {borderBottomRightRadius: 6, borderBottomLeftRadius: 6},
  'rounded-b-lg': {borderBottomRightRadius: 8, borderBottomLeftRadius: 8},
  'rounded-b-xl': {borderBottomRightRadius: 12, borderBottomLeftRadius: 12},
  'rounded-b-2xl': {borderBottomRightRadius: 16, borderBottomLeftRadius: 16},
  'rounded-b-3xl': {borderBottomRightRadius: 24, borderBottomLeftRadius: 24},
  'rounded-b-full': {
    borderBottomRightRadius: 9999,
    borderBottomLeftRadius: 9999,
  },
  'rounded-l-none': {borderTopLeftRadius: 0, borderBottomLeftRadius: 0},
  'rounded-l-sm': {borderTopLeftRadius: 2, borderBottomLeftRadius: 2},
  'rounded-l': {borderTopLeftRadius: 4, borderBottomLeftRadius: 4},
  'rounded-l-md': {borderTopLeftRadius: 6, borderBottomLeftRadius: 6},
  'rounded-l-lg': {borderTopLeftRadius: 8, borderBottomLeftRadius: 8},
  'rounded-l-xl': {borderTopLeftRadius: 12, borderBottomLeftRadius: 12},
  'rounded-l-2xl': {borderTopLeftRadius: 16, borderBottomLeftRadius: 16},
  'rounded-l-3xl': {borderTopLeftRadius: 24, borderBottomLeftRadius: 24},
  'rounded-l-full': {borderTopLeftRadius: 9999, borderBottomLeftRadius: 9999},
  'rounded-ss-none': {borderStartStartRadius: 0},
  'rounded-ss-sm': {borderStartStartRadius: 2},
  'rounded-ss': {borderStartStartRadius: 4},
  'rounded-ss-md': {borderStartStartRadius: 6},
  'rounded-ss-lg': {borderStartStartRadius: 8},
  'rounded-ss-xl': {borderStartStartRadius: 12},
  'rounded-ss-2xl': {borderStartStartRadius: 16},
  'rounded-ss-3xl': {borderStartStartRadius: 24},
  'rounded-ss-full': {borderStartStartRadius: 9999},
  'rounded-se-none': {borderStartEndRadius: 0},
  'rounded-se-sm': {borderStartEndRadius: 2},
  'rounded-se': {borderStartEndRadius: 4},
  'rounded-se-md': {borderStartEndRadius: 6},
  'rounded-se-lg': {borderStartEndRadius: 8},
  'rounded-se-xl': {borderStartEndRadius: 12},
  'rounded-se-2xl': {borderStartEndRadius: 16},
  'rounded-se-3xl': {borderStartEndRadius: 24},
  'rounded-se-full': {borderStartEndRadius: 9999},
  'rounded-ee-none': {borderEndEndRadius: 0},
  'rounded-ee-sm': {borderEndEndRadius: 2},
  'rounded-ee': {borderEndEndRadius: 4},
  'rounded-ee-md': {borderEndEndRadius: 6},
  'rounded-ee-lg': {borderEndEndRadius: 8},
  'rounded-ee-xl': {borderEndEndRadius: 12},
  'rounded-ee-2xl': {borderEndEndRadius: 16},
  'rounded-ee-3xl': {borderEndEndRadius: 24},
  'rounded-ee-full': {borderEndEndRadius: 9999},
  'rounded-es-none': {borderEndStartRadius: 0},
  'rounded-es-sm': {borderEndStartRadius: 2},
  'rounded-es': {borderEndStartRadius: 4},
  'rounded-es-md': {borderEndStartRadius: 6},
  'rounded-es-lg': {borderEndStartRadius: 8},
  'rounded-es-xl': {borderEndStartRadius: 12},
  'rounded-es-2xl': {borderEndStartRadius: 16},
  'rounded-es-3xl': {borderEndStartRadius: 24},
  'rounded-es-full': {borderEndStartRadius: 9999},
  'rounded-tl-none': {borderTopLeftRadius: 0},
  'rounded-tl-sm': {borderTopLeftRadius: 2},
  'rounded-tl': {borderTopLeftRadius: 4},
  'rounded-tl-md': {borderTopLeftRadius: 6},
  'rounded-tl-lg': {borderTopLeftRadius: 8},
  'rounded-tl-xl': {borderTopLeftRadius: 12},
  'rounded-tl-2xl': {borderTopLeftRadius: 16},
  'rounded-tl-3xl': {borderTopLeftRadius: 24},
  'rounded-tl-full': {borderTopLeftRadius: 9999},
  'rounded-tr-none': {borderTopRightRadius: 0},
  'rounded-tr-sm': {borderTopRightRadius: 2},
  'rounded-tr': {borderTopRightRadius: 4},
  'rounded-tr-md': {borderTopRightRadius: 6},
  'rounded-tr-lg': {borderTopRightRadius: 8},
  'rounded-tr-xl': {borderTopRightRadius: 12},
  'rounded-tr-2xl': {borderTopRightRadius: 16},
  'rounded-tr-3xl': {borderTopRightRadius: 24},
  'rounded-tr-full': {borderTopRightRadius: 9999},
  'rounded-br-none': {borderBottomRightRadius: 0},
  'rounded-br-sm': {borderBottomRightRadius: 2},
  'rounded-br': {borderBottomRightRadius: 4},
  'rounded-br-md': {borderBottomRightRadius: 6},
  'rounded-br-lg': {borderBottomRightRadius: 8},
  'rounded-br-xl': {borderBottomRightRadius: 12},
  'rounded-br-2xl': {borderBottomRightRadius: 16},
  'rounded-br-3xl': {borderBottomRightRadius: 24},
  'rounded-br-full': {borderBottomRightRadius: 9999},
  'rounded-bl-none': {borderBottomLeftRadius: 0},
  'rounded-bl-sm': {borderBottomLeftRadius: 2},
  'rounded-bl': {borderBottomLeftRadius: 4},
  'rounded-bl-md': {borderBottomLeftRadius: 6},
  'rounded-bl-lg': {borderBottomLeftRadius: 8},
  'rounded-bl-xl': {borderBottomLeftRadius: 12},
  'rounded-bl-2xl': {borderBottomLeftRadius: 16},
  'rounded-bl-3xl': {borderBottomLeftRadius: 24},
  'rounded-bl-full': {borderBottomLeftRadius: 9999},
  'rounded-4xl': {borderRadius: 32},
  'rounded-5xl': {borderRadius: 40},
  'rounded-s-4xl': {borderStartStartRadius: 32, borderEndStartRadius: 32},
  'rounded-s-5xl': {borderStartStartRadius: 40, borderEndStartRadius: 40},
  'rounded-e-4xl': {borderStartEndRadius: 32, borderEndEndRadius: 32},
  'rounded-e-5xl': {borderStartEndRadius: 40, borderEndEndRadius: 40},
  'rounded-t-4xl': {borderTopLeftRadius: 32, borderTopRightRadius: 32},
  'rounded-t-5xl': {borderTopLeftRadius: 40, borderTopRightRadius: 40},
  'rounded-r-4xl': {borderTopRightRadius: 32, borderBottomRightRadius: 32},
  'rounded-r-5xl': {borderTopRightRadius: 40, borderBottomRightRadius: 40},
  'rounded-b-4xl': {borderBottomRightRadius: 32, borderBottomLeftRadius: 32},
  'rounded-b-5xl': {borderBottomRightRadius: 40, borderBottomLeftRadius: 40},
  'rounded-l-4xl': {borderTopLeftRadius: 32, borderBottomLeftRadius: 32},
  'rounded-l-5xl': {borderTopLeftRadius: 40, borderBottomLeftRadius: 40},
  'rounded-ss-4xl': {borderStartStartRadius: 32},
  'rounded-ss-5xl': {borderStartStartRadius: 40},
  'rounded-se-4xl': {borderStartEndRadius: 32},
  'rounded-se-5xl': {borderStartEndRadius: 40},
  'rounded-ee-4xl': {borderEndEndRadius: 32},
  'rounded-ee-5xl': {borderEndEndRadius: 40},
  'rounded-es-4xl': {borderEndStartRadius: 32},
  'rounded-es-5xl': {borderEndStartRadius: 40},
  'rounded-tl-4xl': {borderTopLeftRadius: 32},
  'rounded-tl-5xl': {borderTopLeftRadius: 40},
  'rounded-tr-4xl': {borderTopRightRadius: 32},
  'rounded-tr-5xl': {borderTopRightRadius: 40},
  'rounded-br-4xl': {borderBottomRightRadius: 32},
  'rounded-br-5xl': {borderBottomRightRadius: 40},
  'rounded-bl-4xl': {borderBottomLeftRadius: 32},
  'rounded-bl-5xl': {borderBottomLeftRadius: 40},
};
