export const flexboxStyles = {
  'flex-1': {flex: 1},
  'just-center': {alignItems: 'center', justifyContent: 'center'},
  'items-start': {alignItems: 'flex-start'},
  'items-end': {alignItems: 'flex-end'},
  'items-center': {alignItems: 'center'},
  'items-baseline': {alignItems: 'baseline'},
  'items-stretch': {alignItems: 'stretch'},
  'justify-start': {justifyContent: 'flex-start'},
  'justify-end': {justifyContent: 'flex-end'},
  'justify-center': {justifyContent: 'center'},
  'justify-between': {justifyContent: 'space-between'},
  'justify-around': {justifyContent: 'space-around'},
  'justify-evenly': {justifyContent: 'space-evenly'},
  'content-normal': {alignContent: 'normal'},
  'content-center': {alignContent: 'center'},
  'content-start': {alignContent: 'flex-start'},
  'content-end': {alignContent: 'flex-end'},
  'content-between': {alignContent: 'space-between'},
  'content-around': {alignContent: 'space-around'},
  'content-evenly': {alignContent: 'space-evenly'},
  'content-baseline': {alignContent: 'baseline'},
  'content-stretch': {alignContent: 'stretch'},
  'justify-items-start': {justifyItems: 'start'},
  'justify-items-end': {justifyItems: 'end'},
  'justify-items-center': {justifyItems: 'center'},
  'justify-items-stretch': {justifyItems: 'stretch'},
};

export const flexDirections = {
  flex: {flexDirection: 'row'},
  'flex-row': {flexDirection: 'row'},
  'flex-row-reverse': {flexDirection: 'row-reverse'},
  'flex-col': {flexDirection: 'column'},
  'flex-col-reverse': {flexDirection: 'column-reverse'},
};

export const flexWrap = {
  'flex-wrap': {flexWrap: 'wrap'},
  'flex-wrap-reverse': {flexWrap: 'wrap-reverse'},
  'flex-nowrap': {flexWrap: 'nowrap'},
};

export const flexGrowShrink = {
  grow: {flexGrow: 1},
  'grow-0': {flexGrow: 0},
  shrink: {flexShrink: 1},
  'shrink-0': {flexShrink: 0},
};

export const flexBasis = {
  'basis-0': {flexBasis: 0},
  'basis-1': {flexBasis: 4},
  'basis-2': {flexBasis: 8},
  'basis-3': {flexBasis: 12},
  'basis-4': {flexBasis: 16},
  'basis-5': {flexBasis: 20},
  'basis-6': {flexBasis: 24},
  'basis-7': {flexBasis: 28},
  'basis-8': {flexBasis: 32},
  'basis-9': {flexBasis: 36},
  'basis-10': {flexBasis: 40},
  'basis-11': {flexBasis: 44},
  'basis-12': {flexBasis: 48},
  'basis-14': {flexBasis: 56},
  'basis-16': {flexBasis: 64},
  'basis-20': {flexBasis: 80},
  'basis-24': {flexBasis: 96},
  'basis-28': {flexBasis: 112},
  'basis-32': {flexBasis: 128},
  'basis-36': {flexBasis: 144},
  'basis-40': {flexBasis: 160},
  'basis-44': {flexBasis: 176},
  'basis-48': {flexBasis: 192},
  'basis-52': {flexBasis: 208},
  'basis-56': {flexBasis: 224},
  'basis-60': {flexBasis: 240},
  'basis-64': {flexBasis: 256},
  'basis-72': {flexBasis: 288},
  'basis-80': {flexBasis: 320},
  'basis-96': {flexBasis: 384},
  'basis-auto': {flexBasis: 'auto'},
  'basis-px': {flexBasis: 1},
  'basis-0.5': {flexBasis: 2},
  'basis-1.5': {flexBasis: 6},
  'basis-2.5': {flexBasis: 10},
  'basis-3.5': {flexBasis: 14},
  'basis-1/2': {flexBasis: '50%'},
  'basis-1/3': {flexBasis: '33.333333%'},
  'basis-2/3': {flexBasis: '66.666667%'},
  'basis-1/4': {flexBasis: '25%'},
  'basis-2/4': {flexBasis: '50%'},
  'basis-3/4': {flexBasis: '75%'},
  'basis-1/5': {flexBasis: '20%'},
  'basis-2/5': {flexBasis: '40%'},
  'basis-3/5': {flexBasis: '60%'},
  'basis-4/5': {flexBasis: '80%'},
  'basis-1/6': {flexBasis: '16.666667%'},
  'basis-2/6': {flexBasis: '33.333333%'},
  'basis-3/6': {flexBasis: '50%'},
  'basis-4/6': {flexBasis: '66.666667%'},
  'basis-5/6': {flexBasis: '83.333333%'},
  'basis-1/12': {flexBasis: '8.333333%'},
  'basis-2/12': {flexBasis: '16.666667%'},
  'basis-3/12': {flexBasis: '25%'},
  'basis-4/12': {flexBasis: '33.333333%'},
  'basis-5/12': {flexBasis: '41.666667%'},
  'basis-6/12': {flexBasis: '50%'},
  'basis-7/12': {flexBasis: '58.333333%'},
  'basis-8/12': {flexBasis: '66.666667%'},
  'basis-9/12': {flexBasis: '75%'},
  'basis-10/12': {flexBasis: '83.333333%'},
  'basis-11/12': {flexBasis: '91.666667%'},
  'basis-full': {flexBasis: '100%'},
};
