export const overflowStyles = {
  'overflow-auto': {overflow: 'auto'},
  'overflow-hidden': {overflow: 'hidden'},
  'overflow-clip': {overflow: 'clip'},
  'overflow-visible': {overflow: 'visible'},
  'overflow-scroll': {overflow: 'scroll'},
  'overflow-x-auto': {overflowX: 'auto'},
  'overflow-y-auto': {overflowY: 'auto'},
  'overflow-x-hidden': {overflowX: 'hidden'},
  'overflow-y-hidden': {overflowY: 'hidden'},
  'overflow-x-clip': {overflowX: 'clip'},
  'overflow-y-clip': {overflowY: 'clip'},
  'overflow-x-visible': {overflowX: 'visible'},
  'overflow-y-visible': {overflowY: 'visible'},
  'overflow-x-scroll': {overflowX: 'scroll'},
  'overflow-y-scroll': {overflowY: 'scroll'},
};

export const positionStyles = {
  static: {position: 'static'},
  fixed: {position: 'fixed'},
  absolute: {position: 'absolute'},
  relative: {position: 'relative'},
  'z-0': {zIndex: 0},
  'z-10': {zIndex: 10},
  'z-20': {zIndex: 20},
  'z-30': {zIndex: 30},
  'z-40': {zIndex: 40},
  'z-50': {zIndex: 50},
  'z-auto': {zIndex: 'auto'},
};

export const opacityStyles = {
  'opacity-0': {opacity: 0},
  'opacity-5': {opacity: 0.05},
  'opacity-10': {opacity: 0.1},
  'opacity-15': {opacity: 0.15},
  'opacity-20': {opacity: 0.2},
  'opacity-25': {opacity: 0.25},
  'opacity-30': {opacity: 0.3},
  'opacity-35': {opacity: 0.35},
  'opacity-40': {opacity: 0.4},
  'opacity-45': {opacity: 0.45},
  'opacity-50': {opacity: 0.5},
  'opacity-55': {opacity: 0.55},
  'opacity-60': {opacity: 0.6},
  'opacity-65': {opacity: 0.65},
  'opacity-70': {opacity: 0.7},
  'opacity-75': {opacity: 0.75},
  'opacity-80': {opacity: 0.8},
  'opacity-85': {opacity: 0.85},
  'opacity-90': {opacity: 0.9},
  'opacity-95': {opacity: 0.95},
  'opacity-100': {opacity: 1},
};

export const absolutePositionStyles = {
  'inset-0': {top: 0, left: 0, right: 0, bottom: 0},
  'inset-x-0': {left: 0, right: 0},
};
